### ISSUE TITLE
the value range of lab space

### ISSUE THREAD

**Issue by qivigor** [jorge-pessoa/pytorch-colors#3]
I want to know the value range of lab space. 
when I use the 'colors.lab_to_rgb' , I got a UserWarning: Color data out of range: Z < 0 in 42194 pixels.

**Comment by jorge-pessoa** [comment]
Hello,

I apologize for the delay in answering. The underlying implementation by scikit-image uses the following value ranges for LAB: 
L (0-100), a (-128-127), b (-128-127). For a proper conversion you will need to scale your image for these ranges.
