### ISSUE TITLE
xyz conversion doesn't work

### ISSUE THREAD

**Issue by sepideh-srj** [jorge-pessoa/pytorch-colors#5]
Hi, I wanted to use the rgb to xyz and vice versa conversion, so first I did a little test to make sure the code is working correctly and it seems it's not, here is my code: 
(A is a tensor of size (3,256,256))
A = torch.reshape(A,(1,3,256,256))
A = colors.rgb_to_xyz(A)
A = colors.xyz_to_rgb(A)
A = torch.reshape(A,(3,256,256))
A = tensor2im(A)
When I look at the image after these conversions the image looks very different than what it should be (as you can see in the figure, top is input image, bottom is output.) If I use hsv instead of xyz it works correctly so I guess it's only the problem with xyz.
![Figure_1](https://user-images.githubusercontent.com/12370175/99340222-78840980-283c-11eb-897c-b91889904c69.png)

**Comment by jorge-pessoa** [comment]
I've tested this with  the latest scikit-image package version and was unable to reproduce this problem. Could you update and re-test? If the problem persists please re-open a new issue.

Thank you.
